### ISSUE TITLE
Queue is huge atm and hasn't been updated in ages

### ISSUE THREAD

**Issue by theonlygusti** [anime-plus/graph#22]

**Comment by simoconfa** [comment]
I think it might be because of [this](https://www.reddit.com/r/anime/comments/8lyvqp/mal_is_disabling_3rd_party_apps/).
For lazy people: MAL API has been temporanely disabled
I this source code is based on it, graph will never scan user profiles

**Comment by theonlygusti** [comment]
Oh it's still down? For some reason I assumed they'd put it back up again once I was able to get back into my account, but it makes sense that it's still down.

**Comment by simoconfa** [comment]
Honestly speaking I don't know. Maybe it is only an html agility problem so bot cannot accept the new EU conditions so MAL does not let it navigate. But the most reasonable hypothesis is the API one.

**Comment by theonlygusti** [comment]
I've gone backwards in the queue since yesterday, was 300-sometng, am now 900-someting

**Comment by simoconfa** [comment]
Update: MAL is up again, but the queue is blocked since yesterday

**Comment by twdarkeh** [comment]
Seems to be fine now, though updates are taking awhile and aren't 100% accurate the first time.
