### ISSUE TITLE
[Bug] List scraper only grabs the first 300 entries

### ISSUE THREAD

**Issue by ekrekeler** [anime-plus/graph#25]
Ever since MAL changed their anime and manga list pages, they only display the first 300 entries before the user scrolls to the bottom of the page. This also means that the scraping function will only grab the first 300 entries, even if there are more that aren't loaded.

**Comment by gineika** [comment]
Our bot can get all entries. If you see only 300, update your profile again.

**Comment by ekrekeler** [comment]
I'm sorry, you are correct. I am looking at [Gigguk's profile](https://myanimelist.net/profile/gigguk) in particular, and it looks like an internal issue on MAL's side. His profile lists 202 completed anime, while there are clearly 300+ completed on his list.
