### ISSUE TITLE
How is the threshold computed?

### ISSUE THREAD

**Issue by byDave251** [anime-plus/graph#27]
Hello, I looked at the files with the achievments. Could you please mention it in the markdown file with achievments?

**Comment by gineika** [comment]
"Thresholds for manga/anime genres are 1.5/3% of titles (up to 25/50) for level 1, 3/6% (up to 50/100) for level 2, 6/12% (up to 100/200) for level 3 and 12/24% (up to 200/400) for the maximum level."
