### ISSUE TITLE
Episode Count

### ISSUE THREAD

**Issue by VinnieMuffinMan** [anime-plus/graph#34]
When counting the number of episodes watched, it doesn’t count the in-between episodes. For example, if there were entries for 2nd and 5th episode, only 2 would be counted, not 5.

**Comment by KanChiMoe** [comment]
So, if I understand that correctly:

If you mark down that you've watched episode 2, and episode 5 - it only marks down 2?
That sounds like it's working, because you've only marked down you've watched 2 episodes - episode 2, and 5.

What happens if you mark down watching episode 1, 2 and 5?

**Comment by VinnieMuffinMan** [comment]
It only counts how many times you update your watched episodes on the recent history page. If you said that you watched 1, then changed it to 2, then to 5, it counts that you watched 3 episodes.

**Comment by gineika** [comment]
Increase episode count one by one (+), otherwise MAL will exclude episodes from your history page (https://myanimelist.net/history/username).
