### ISSUE TITLE
Total Time spent Achievment

### ISSUE THREAD

**Issue by Boogy444** [anime-plus/graph#43]
Hey. Is the achievment supposed to not add time spend from Re-Watched anime aswell? since that should be added aswell to the "total", otherwise is just Time spent on first time watched/completed episodes or so...

Thank you :)

![image](https://user-images.githubusercontent.com/81272087/112237715-e78ac800-8c4b-11eb-9b25-54607ba82b3b.png)
![image](https://user-images.githubusercontent.com/81272087/112237756-fc675b80-8c4b-11eb-991f-83f51b4f17f8.png)

**Comment by gineika** [comment]
We don't count rewatched episodes. Because we don't have access to that information.
