### ISSUE TITLE
Achievement for high dropped anime/manga count

### ISSUE THREAD

**Issue by ngoomie** [anime-plus/graph#49]
As a counterpart to the Completionist achievement, I'd like to suggest having an achievement for people who have large amounts of dropped anime/manga, just like how the mean score set of achievements has achievements both for a high mean score as well as low ones.

Seems like it'd be neat to have, considering I don't usually see high drop counts on MAL. I feel like the most I've seen from other people has been...maybe 30? Though if there were a drop count achievement, I'd personally think it'd be better for it to be something above that number, or maybe even something like awarding it depending on the ratio of dropped to completed anime.

**Comment by gineika** [comment]
We don't want to encourage people to drop more anime.
