### ISSUE TITLE
Anime Originals achievement missing recent titles

### ISSUE THREAD

**Issue by yeahthatantonio** [anime-plus/graph#54]
I noticed the list of titles for the Original anime achievement hasn't been updated since around the Summer 2020 season, which I'm assuming is because it's a hassle to manually grab each individual title number.  I had some free time and went ahead did it myself for Fall 2020 through Winter 2024 -- I've attached a "MAL originals.txt" file with titles that you can add to your title list in the .json, and I've also included a "MAL originals with titles.txt" file in case you wanted to double-check the validity of what these anime are.  I left out stuff that had less than 1K members or didn't have enough information for me to know if they were actually originals, but this should have all the big ones from the last few years.

Would love if you could add these!
[MAL originals.txt](https://github.com/anime-plus/graph/files/14898910/MAL.originals.txt)
[MAL originals with titles.txt](https://github.com/anime-plus/graph/files/14898911/MAL.originals.with.titles.txt)

**Comment by gineika** [comment]
Thank you!
